# Generated by Django 2.2.12 on 2020-05-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('label', models.CharField(max_length=10)),
                ('data_source', models.CharField(max_length=10)),
            ],
        ),
    ]
