# Generated by Django 2.2.12 on 2020-05-31 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20200531_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
